[package]
name = "keyman_keyboard_processor"
version = "0.1.0"
# This is required for 2018 support of Rust
edition = "2018"

[lib]
name = "keyman_keyboard_processor"
crate-type = ["dylib", "rlib"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true