[package]
name = "keyman_keyboard_processor_wasm"
version = "0.1.0"
# This is required for 2018 support of Rust
edition = "2018"

[lib]
name = "keyman_keyboard_processor_wasm"
crate-type = ["staticlib", "cdylib"]

[dependencies]
keyman_keyboard_processor = { path = "../keyman_keyboard_processor" }
wasm-bindgen = "0.2.63"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true