[package]
name = "rust_mock_processor"
version = "0.1.0"
# This is required for 2018 support of Rust
edition = "2018"

[features]
# We only need to enable wasm dependencies for the
# wasm target
wasm = ["wasm-bindgen"]
native = []

[lib]
name = "rust_mock_processor"
crate-type = ["staticlib", "cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2.63", optional = true }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true