[package]
name = "rust_mock_processor"
version = "0.1.0"
# This is required for 2018 support of Rust
edition = "2018"

[lib]
name = "rust_mock_processor"
crate-type = ["staticlib", "cdylib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.63"

[dependencies]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true